### PR TITLE
Feat/rotary dimmer command class parameters

### PR DESCRIPTION
**Pull request by aasmundbo**
I got around to do this faster than I expected. 

Added all the configuration parameters to the rotary dimmer. 
Default dimming speed and default brightness does not seem to have any effect (or it doesn't match the user manual). 

Delay time when turning load off also applies then turning load on.

### CODE REVIEW

**Comment by fiLLLip** [comment]
If you resolve the conflicts we can get this in :+1:

**Comment by aasmundbo** [comment]
Will resolve once I get time to sit down and do it. This branch is based on master, I’ll base it on the other dimmer branch instead

**Comment by fiLLLip** [comment]
I think the master was updated since you branched out, so rebase on current master should be fine :)

**Comment by aasmundbo** [comment]
Branch rebased on top of master. Please review and merge, @fiLLLip.

**Comment by fiLLLip** [comment]
LGTM!

**Pull request merged**
